import { MOCK_PROJECT_SUMMARIES } from "../projects/mock-projects-data";
import type { Issue } from "./issue-types";
import { seedIssueComments } from "./mock-issue-comments";

const RAW_ISSUES: Omit<
  Issue,
  "comments" | "commentCount" | "activity" | "labels" | "watchers"
>[] = [
  {
    id: "i1",
    number: 142,
    title: "Fix crash on cold start",
    description:
      "App crashes when launched without network connectivity.\n\n**Steps to reproduce:**\n1. Enable airplane mode\n2. Force-quit the app\n3. Relaunch",
    status: "todo",
    priority: "critical",
    assignee: "Grace Hopper",
    assigneeInitials: "GH",
    reporter: "Ada Lovelace",
    reporterInitials: "AL",
    projectId: "p1",
    projectKey: "MOB",
    projectName: "Mobile App",
    projectColor: "#4F46E5",
    dueDate: new Date("2026-07-19T17:00:00"),
    createdAt: new Date("2026-07-15T09:00:00"),
    updatedAt: new Date("2026-07-22T14:30:00"),
  },
  {
    id: "i2",
    number: 141,
    title: "Add pagination to issues list",
    description: "Cursor-based pagination for large orgs.",
    status: "in_progress",
    priority: "high",
    assignee: "Alan Turing",
    assigneeInitials: "AT",
    reporter: "Ada Lovelace",
    reporterInitials: "AL",
    projectId: "p2",
    projectKey: "API",
    projectName: "Backend API",
    projectColor: "#0891B2",
    dueDate: new Date("2026-07-28T17:00:00"),
    createdAt: new Date("2026-07-10T11:00:00"),
    updatedAt: new Date("2026-07-22T11:15:00"),
  },
  {
    id: "i3",
    number: 140,
    title: "Update button component tokens",
    description: "Align primary button with new brand palette.",
    status: "in_review",
    priority: "medium",
    assignee: "Ada Lovelace",
    assigneeInitials: "AL",
    reporter: "Grace Hopper",
    reporterInitials: "GH",
    projectId: "p3",
    projectKey: "DS",
    projectName: "Design System",
    projectColor: "#DB2777",
    dueDate: new Date("2026-07-21T17:00:00"),
    createdAt: new Date("2026-07-08T14:00:00"),
    updatedAt: new Date("2026-07-21T16:45:00"),
  },
  {
    id: "i4",
    number: 139,
    title: "Implement refresh token rotation",
    description: "Rotate refresh tokens on each use.",
    status: "done",
    priority: "high",
    assignee: "Alan Turing",
    assigneeInitials: "AT",
    reporter: "Alan Turing",
    reporterInitials: "AT",
    projectId: "p2",
    projectKey: "API",
    projectName: "Backend API",
    projectColor: "#0891B2",
    dueDate: new Date("2026-07-18T17:00:00"),
    createdAt: new Date("2026-07-01T10:00:00"),
    updatedAt: new Date("2026-07-20T09:00:00"),
  },
  {
    id: "i5",
    number: 138,
    title: "Offline mode indicator",
    description: "Show banner when device loses connectivity.",
    status: "backlog",
    priority: "medium",
    assignee: null,
    assigneeInitials: null,
    reporter: "Ada Lovelace",
    reporterInitials: "AL",
    projectId: "p1",
    projectKey: "MOB",
    projectName: "Mobile App",
    projectColor: "#4F46E5",
    dueDate: new Date("2026-07-17T17:00:00"),
    createdAt: new Date("2026-07-12T08:00:00"),
    updatedAt: new Date("2026-07-19T13:20:00"),
  },
  {
    id: "i8",
    number: 135,
    title: "Remove deprecated v1 endpoints",
    description: "Sunset legacy API routes after migration window.",
    status: "cancelled",
    priority: "low",
    assignee: "Alan Turing",
    assigneeInitials: "AT",
    reporter: "Grace Hopper",
    reporterInitials: "GH",
    projectId: "p2",
    projectKey: "API",
    projectName: "Backend API",
    projectColor: "#0891B2",
    dueDate: null,
    createdAt: new Date("2026-06-20T12:00:00"),
    updatedAt: new Date("2026-07-17T15:00:00"),
  },
  {
    id: "i6",
    number: 137,
    title: "Document spacing scale",
    description: "Add spacing tokens to Storybook.",
    status: "done",
    priority: "low",
    assignee: "Ada Lovelace",
    assigneeInitials: "AL",
    reporter: "Ada Lovelace",
    reporterInitials: "AL",
    projectId: "p3",
    projectKey: "DS",
    projectName: "Design System",
    projectColor: "#DB2777",
    dueDate: new Date("2026-07-10T17:00:00"),
    createdAt: new Date("2026-07-05T10:00:00"),
    updatedAt: new Date("2026-07-18T10:30:00"),
  },
  {
    id: "i7",
    number: 136,
    title: "Rate limit export endpoints",
    description: "Apply plan-tier rate limits to CSV export.",
    status: "in_progress",
    priority: "medium",
    assignee: "Grace Hopper",
    assigneeInitials: "GH",
    reporter: "Ada Lovelace",
    reporterInitials: "AL",
    projectId: "p2",
    projectKey: "API",
    projectName: "Backend API",
    projectColor: "#0891B2",
    dueDate: new Date("2026-07-20T17:00:00"),
    createdAt: new Date("2026-07-14T09:00:00"),
    updatedAt: new Date("2026-07-22T08:00:00"),
  },
];

export const MOCK_ISSUES: Issue[] = RAW_ISSUES.map(seedIssueComments);

export const MOCK_PROJECTS = MOCK_PROJECT_SUMMARIES;

export const MOCK_TEAM_MEMBERS = [
  { name: "Ada Lovelace", initials: "AL" },
  { name: "Alan Turing", initials: "AT" },
  { name: "Grace Hopper", initials: "GH" },
];

export const MOCK_CURRENT_USER = "Ada Lovelace";
