/** Machine-readable error codes aligned with DomainError.code. */
export enum ErrorCode {
  AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
  ASSIGNEE_NOT_ORG_MEMBER = "ASSIGNEE_NOT_ORG_MEMBER",
  BILLING_ALREADY_SUBSCRIBED = "BILLING_ALREADY_SUBSCRIBED",
  COMMENT_RATE_LIMIT_EXCEEDED = "COMMENT_RATE_LIMIT_EXCEEDED",
  CONFLICT = "CONFLICT",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  EMAIL_VERIFICATION_CODE_INVALID = "EMAIL_VERIFICATION_CODE_INVALID",
  EMAIL_VERIFICATION_RESEND_COOLDOWN = "EMAIL_VERIFICATION_RESEND_COOLDOWN",
  EXPORT_NOT_FOUND = "EXPORT_NOT_FOUND",
  EXPORT_QUOTA_EXCEEDED = "EXPORT_QUOTA_EXCEEDED",
  FORBIDDEN = "FORBIDDEN",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  ISSUE_CONFLICT = "ISSUE_CONFLICT",
  ISSUE_STATUS_TRANSITION = "ISSUE_STATUS_TRANSITION",
  NOT_FOUND = "NOT_FOUND",
  ORG_INVITE_ALREADY_PENDING = "ORG_INVITE_ALREADY_PENDING",
  ORG_INVITE_NOT_FOUND = "ORG_INVITE_NOT_FOUND",
  ORG_MEMBER_ALREADY_EXISTS = "ORG_MEMBER_ALREADY_EXISTS",
  ORG_MEMBER_LIMIT_EXCEEDED = "ORG_MEMBER_LIMIT_EXCEEDED",
  ORG_PROJECT_LIMIT_EXCEEDED = "ORG_PROJECT_LIMIT_EXCEEDED",
  PROJECT_ARCHIVED = "PROJECT_ARCHIVED",
  PROJECT_KEY_ALREADY_EXISTS = "PROJECT_KEY_ALREADY_EXISTS",
  PROJECT_NAME_ALREADY_EXISTS = "PROJECT_NAME_ALREADY_EXISTS",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  UNAUTHORIZED = "UNAUTHORIZED",
  UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY",
  VALIDATION_ERROR = "VALIDATION_ERROR",
}

export enum ErrorMessage {
  AUTH_EMAIL_ALREADY_EXISTS = "An account with this email already exists",
  ASSIGNEE_NOT_ORG_MEMBER = "Assignee must be a member of the organization",
  BILLING_ALREADY_SUBSCRIBED = "This organization is already subscribed",
  COMMENT_RATE_LIMIT_EXCEEDED = "Too many comments. Please try again later",
  CONFLICT = "Conflict",
  EMAIL_NOT_VERIFIED = "Please verify your email before logging in",
  EMAIL_VERIFICATION_CODE_INVALID = "Invalid or expired code.",
  EMAIL_VERIFICATION_RESEND_COOLDOWN = "Please wait before requesting a new code.",
  EXPORT_NOT_FOUND = "Export not found",
  EXPORT_QUOTA_EXCEEDED = "CSV export quota exceeded for this month",
  FORBIDDEN = "You are not authorized to perform this action",
  INTERNAL_SERVER_ERROR = "Something went wrong. Please try again",
  INVALID_CREDENTIALS = "Invalid credentials",
  ISSUE_CONFLICT = "Issue changed since you last viewed it",
  ISSUE_STATUS_TRANSITION = "This status change is not allowed",
  NOT_FOUND = "Not found",
  ORG_INVITE_ALREADY_PENDING = "An active invite for this email already exists",
  ORG_INVITE_NOT_FOUND = "Invite not found",
  ORG_MEMBER_ALREADY_EXISTS = "An organization member with this user and organization already exists",
  ORG_MEMBER_LIMIT_EXCEEDED = "Organization member limit reached for this plan",
  ORG_PROJECT_LIMIT_EXCEEDED = "Organization project limit reached for this plan",
  PROJECT_ARCHIVED = "This project is archived",
  PROJECT_KEY_ALREADY_EXISTS = "A project with this key already exists",
  PROJECT_NAME_ALREADY_EXISTS = "A project with this name already exists",
  TOO_MANY_REQUESTS = "Too many requests. Please try again later",
  UNAUTHORIZED = "Unauthorized",
  UNPROCESSABLE_ENTITY = "Unprocessable entity",
  VALIDATION_ERROR = "Validation errors in your request",
}
