const EMAIL_VERIFICATION_CODE_DURATION_MINS = 10;
const EMAIL_VERIFICATION_VERIFY_MAX_ATTEMPTS = 3;
const EMAIL_VERIFICATION_RESEND_BASE_COOLDOWN_SECS = 60;
const EMAIL_VERIFICATION_RESEND_COOLDOWN_MULTIPLIER = 5;
const EMAIL_VERIFICATION_RESEND_MAX = 5;
const EMAIL_VERIFICATION_RESEND_LOCKOUT_HOURS = 24;

export const AUTH_CONSTANTS = {
  EMAIL_VERIFICATION_CODE_DURATION_MINS,
  EMAIL_VERIFICATION_RESEND_LIMITS: {
    baseCooldownSecs: EMAIL_VERIFICATION_RESEND_BASE_COOLDOWN_SECS,
    cooldownMultiplier: EMAIL_VERIFICATION_RESEND_COOLDOWN_MULTIPLIER,
    lockoutHours: EMAIL_VERIFICATION_RESEND_LOCKOUT_HOURS,
    maxResends: EMAIL_VERIFICATION_RESEND_MAX,
  },
  EMAIL_VERIFICATION_VERIFY_LIMITS: {
    maxAttempts: EMAIL_VERIFICATION_VERIFY_MAX_ATTEMPTS,
  },
  JWT_STRATEGY: "AUTH_USER",
  ORG_ID_HEADER: "x-org-id",
};
